### ISSUE TITLE
Support for modifications to objects

### ISSUE THREAD

**Issue by anandology** [anandology/pycle#1]
While pycle supports assignments correctly, it can't recognize the mutations to objects. For example, the following test fails:

```yaml
name: test references
code: |
  numbers = [1, 2, 3, 4, 5]
  numbers.append(6)
env:
  numbers: [1, 2, 3, 4, 5, 6]
```

Pycle works by hijacking the `__setattr__` on globals and that approach only works for assignments.

There seems to be two approaches to solve this. 

1. save all the available variables at the end of the session
2. implement a cloudpickle like serialization capability that is db-aware

The first approach has a flaw. If there are two variables refer to the same list, there will be two different lists after loading back. To resolve this, we need to pickle the entire env as a single item and dump into the db. While that works, we'll have to load all the variables at the beginning of the next execution, even if we don't use all the variables. 

It sounds like a fair to compromize on the performance in the short run for correctness.
